'\" t
.\"     Title: pcp_promote_node
.\"    Author: The Pgpool Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 2020
.\"    Manual: Pgpool-II 4.2.2 文書
.\"    Source: Pgpool-II 4.2.2
.\"  Language: Japanese
.\"
.TH "PCP_PROMOTE_NODE" "1" "2020" "Pgpool-II 4.2.2" "Pgpool-II 4.2.2 文書"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "名前"
pcp_promote_node \- Pgpool\-II のノードをプライマリに昇格させる
.SH "概要"
.HP \w'\fBpcp_promote_node\fR\ 'u
\fBpcp_promote_node\fR [\fIoptions\fR...] [\fInode_id\fR] [\fIgracefully\fR]
.SH "説明"
.PP
\fBpcp_promote_node\fR
は
Pgpool\-II
のノードをプライマリに昇格させます。 これは、ストリーミングレプリケーション構成の場合のみ使用できます。 このコマンドは実際に
PostgreSQL
のスタンバイサーバを昇格するわけではないことに注意してください。 単に
Pgpool\-II
の内部ステータスを変更するだけです。 ですから、ユーザはこのコマンドを使う際には自分で
PostgreSQL
のスタンバイを昇格させるようにしてください。
.PP
\fBpcp_promote_node\fRは、起動された後以下を行います。
follow_primary_commandが設定されている場合はそれも起動されるので、十分な注意が必要です。 通常はfollow_primary_commandを無効にしてからこのコマンドを実行することをお勧めします。
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
指定されたスタンバイPostgreSQLのステータスをstandbyからprimaryに変更します。 これはPgpool\-II
の内部ステータスを変更するだけで、実際にPostgreSQL
のスタンバイサーバを昇格するわけではありません。
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
引数で指定された以外のPostgreSQLノードのステータスをdownに変更します。 これはPgpool\-II
の内部ステータスを変更するだけで、実際にPostgreSQLのスタンバイサーバをダウンさせるわけではありません。
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
follow_primary_commandが設定されている場合は、2でダウンさせたPostgreSQLノードに対してfollow_primary_commandを実行します。
.RE
.sp
.SH "オプション"
.PP
.PP
\fB\-n \fR\fB\fInode_id\fR\fR
.br
\fB\-\-node\-id=\fR\fB\fInode_id\fR\fR
.RS 4
プライマリに昇格させるバックエンドノードのインデックスを指定します。
.RE
.PP
\fB\-g \fR
.br
\fB\-\-gracefully\fR
.RS 4
すべてのクライアントが接続を終了するまでノードを復帰しません。 （ただし、client_idle_limit_in_recovery
が \-1 あるいは、
recovery_timeout
が設定されている場合を除く）
.RE
.PP
\fBその他 \fR
.RS 4
\fBpcp_common_options\fR(1)
を参照してください。
.RE
