'\" t
.\"     Title: wd_cli
.\"    Author: The Pgpool Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 2021
.\"    Manual: Pgpool-II 4.2.5 文書
.\"    Source: Pgpool-II 4.2.5
.\"  Language: Japanese
.\"
.TH "WD_CLI" "1" "2021" "Pgpool-II 4.2.5" "Pgpool-II 4.2.5 文書"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "名前"
wd_cli \- 外部ヘルスチェックシステムとの統合に用いるためのWatchdog Command Line Interface (CLI)ユーティリティ
.SH "概要"
.HP \w'\fBwd_cli\fR\ 'u
\fBwd_cli\fR [\fIoperation\fR...] [\fInode\ search\ option\fR...] [\fIoption\fR...]
.SH "DESCRIPTION"
.PP
\fBwd_cli\fR
watchdogとヘルスチェック関連のノード操作を行うための便利で使いやすいインターフェイスを提供します。
.SH "操作"
.PP
.PP
\fB\-i\fR
.br
\fB\-\-info\fR
.RS 4
ノードの検索条件に基づいてノード状態を取得します。
.RE
.PP
\fB\-I \fR\fB\fINEW_STATUS\fR\fR
.br
\fB\-\-inform=\fR\fB\fINEW_STATUS\fR\fR
.RS 4
watchdogノード状態を更新します。 受付可能な値はDEADとALIVEです。
.RE
.SH "ノード検索操作"
.PP
.PP
\fB\-a \fR
.br
\fB\-\-all\fR
.RS 4
すべてのノードを選択します。（\-\-info操作でのみ可能です）
.RE
.PP
\fB\-n \fR\fB\fIWATCHDOG_NODE_ID\fR\fR
.br
\fB\-\-node\-id=\fR\fB\fIWATCHDOG_NODE_ID\fR\fR
.RS 4
node_idでwatchdogノードを検索します。
.RE
.PP
\fB\-N \fR\fB\fINODE_NAME\fR\fR
.br
\fB\-\-node\-name=\fR\fB\fINODE_NAME\fR\fR
.RS 4
名前でwatchdogノードを検索します。
.RE
.PP
\fB\-H \fR\fB\fIHOSTNAME\fR\fR
.br
\fB\-\-node\-host=\fR\fB\fIHOSTNAME\fR\fR
.RS 4
ホスト名でwatchdogノードを検索します。
.RE
.PP
\fB\-P \fR\fB\fIPORT_NO\fR\fR
.br
\fB\-\-node\-port=\fR\fB\fIPORT_NO\fR\fR
.RS 4
ポート番号でwatchdogノードを検索します。
.RE
.SH "操作"
.PP
.PP
\fB\-k \fR\fB\fIKEY\fR\fR
.br
\fB\-\-auth\-key=\fR\fB\fIKEY\fR\fR
.RS 4
watchdog認証キー。 この認証キーを指定するとpgpool\&.conf\->wd_authkeyの値に優先します。
.RE
.PP
\fB\-f \fR\fB\fICONFIG_FILE\fR\fR
.br
\fB\-\-config\-file=\fR\fB\fICONFIG_FILE\fR\fR
.RS 4
pgpool\&.conf
file\&.
.RE
.PP
\fB\-s \fR\fB\fISOCKET_DIR\fR\fR
.br
\fB\-\-socket\-dir=\fR\fB\fISOCKET_DIR\fR\fR
.RS 4
watchdog IPCソケットディレクトリのパスです。 このパスを指定するとpgpool\&.conf\->wd_ipc_socket_dirの値に優先します。
.RE
.PP
\fB\-p \fR\fB\fIPORT_NO\fR\fR
.br
\fB\-\-ipc\-port=\fR\fB\fIPORT_NO\fR\fR
.RS 4
watchdog IPCソケットのポート番号です。 このポート番号を指定するとpgpool\&.conf\->wd_portの値に優先します。
.RE
.PP
\fB\-m \fR\fB\fImessage_string\fR\fR
.br
\fB\-\-message=\fR\fB\fImessage_string\fR\fR
.RS 4
ノード状態とともにPgpool\-IIに渡す追加のメッセージ文字列です。
.RE
.PP
\fB\-v\fR
.br
\fB\-\-verbose\fR
.RS 4
冗長なメッセージを有効にします。
.RE
.PP
\fB\-V\fR
.br
\fB\-\-version\fR
.RS 4
バージョン情報を表示します。
.RE
.PP
\fB\-d\fR
.br
\fB\-\-debug\fR
.RS 4
デバッグ表示を有効にします。
.RE
.PP
\fB\-h\fR
.br
\fB\-\-help\fR
.RS 4
\fBwd_cli\fRのヘルプを表示します。
.RE
.SH "例"
.PP
Pgpool\-IIクラスタを監視するために外部ヘルスチェックシステムが設定されていて、ノード障害を検出しました。 この情報をPgpool\-IIクラスタに渡して適切な対応を行うことができるようにwd_cliユーティリティを使用することができます。
.sp
.if n \{\
.RS 4
.\}
.nf
    #inform Pgpool\-II about node named RN\-110 failure
    wd_cli \-\-inform DEAD \-N \*(AqRN\-110\*(Aq \-p 9001 \-m \*(AqPgpool node with name RN\-110 is not reachable\*(Aq
   
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
    #inform Pgpool\-II about node\-id 10 failure
    wd_cli \-\-inform DEAD \-n 10 \-m \*(AqPgpool node with ID 10 is not responding\*(Aq
   
.fi
.if n \{\
.RE
.\}
.sp
同様にノードが再び復帰したことをPgpool\-IIに知らせます。
.sp
.if n \{\
.RS 4
.\}
.nf
    #inform Pgpool\-II about node\-id 10 re\-joining
    wd_cli \-\-inform ALIVE \-n 10 \-m \*(AqPgpool node with ID 10 is reachable again\*(Aq
   
.fi
.if n \{\
.RE
.\}
.sp
また、wd_cliはノードの現在の状態を取得するために使用することができます。
.sp
.if n \{\
.RS 4
.\}
.nf
    wd_cli \-f simple_conf/watchdog/pgpool_wd1\&.conf \-\-info \-v \-\-all

	Total Watchdog nodes configured for lifecheck:  2
	*****************
	Node ID:           0
	Node Status code   4
	Node Status:       LEADER
	Node Name:         localhost:9991 Linux localhost\&.localdomain
	Node Host:         localhost
	Node WD Port:      9001
	Node Pgpool Port:  9991

	Node ID:           1
	Node Status code   7
	Node Status:       STANDBY
	Node Name:         localhost:9992 Linux localhost\&.localdomain
	Node Host:         localhost
	Node WD Port:      9002
	Node Pgpool Port:  9992
   
.fi
.if n \{\
.RE
.\}
.sp

